<?php

declare(strict_types=1);

/*
 * This file is part of the PHPRegex package.
 *
 * (c) Younes ENNAJI <younes.ennaji.pro@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace PHPRegex\Toolkit\Upgrade;

/**
 * What 1.3 named, and what 2.0 names it: every class 1.3 shipped, its legacy
 * aliases included, the enum cases renamed and the methods renamed. The
 * upgrade guide's tables and the Rector set read it.
 *
 * @internal
 */
final class UpgradeMap
{
    /**
     * A 1.3 class => its 2.0 name.
     */
    public const RENAMED = [
        'RegexParser\\AnalysisReport' => \PHPRegex\Toolkit\AnalysisReport::class,
        'RegexParser\\Automata\\Alphabet\\CharSet' => \PHPRegex\Automata\Alphabet\CharSet::class,
        'RegexParser\\Automata\\Api\\RegexLanguageSolver' => \PHPRegex\Automata\LanguageSolver::class,
        'RegexParser\\Automata\\AstToNfaTransformer' => \PHPRegex\Automata\Transform\AstToNfaTransformer::class,
        'RegexParser\\Automata\\AstToNfaTransformerInterface' => \PHPRegex\Automata\Transform\AstToNfaTransformerInterface::class,
        'RegexParser\\Automata\\Builder\\DfaBuilder' => \PHPRegex\Automata\Builder\DfaBuilder::class,
        'RegexParser\\Automata\\Builder\\NfaBuilder' => \PHPRegex\Automata\Builder\NfaBuilder::class,
        'RegexParser\\Automata\\CharSet' => \PHPRegex\Automata\Alphabet\CharSet::class,
        'RegexParser\\Automata\\Determinization\\DeterminizationAlgorithm' => \PHPRegex\Automata\Determinization\DeterminizationAlgorithm::class,
        'RegexParser\\Automata\\Determinization\\DeterminizationAlgorithmFactory' => \PHPRegex\Automata\Determinization\DeterminizationAlgorithmFactory::class,
        'RegexParser\\Automata\\Determinization\\DeterminizationAlgorithmInterface' => \PHPRegex\Automata\Determinization\DeterminizationAlgorithmInterface::class,
        'RegexParser\\Automata\\Determinization\\SubsetConstruction' => \PHPRegex\Automata\Determinization\SubsetConstruction::class,
        'RegexParser\\Automata\\Determinization\\SubsetConstructionIndexed' => \PHPRegex\Automata\Determinization\SubsetConstructionIndexed::class,
        'RegexParser\\Automata\\Determinization\\WorkBudgetAwareDeterminizationAlgorithmInterface' => \PHPRegex\Automata\Determinization\WorkBudgetAwareDeterminizationAlgorithmInterface::class,
        'RegexParser\\Automata\\Dfa' => \PHPRegex\Automata\Model\Dfa::class,
        'RegexParser\\Automata\\DfaBuilder' => \PHPRegex\Automata\Builder\DfaBuilder::class,
        'RegexParser\\Automata\\DfaMinimizer' => \PHPRegex\Automata\Minimization\DfaMinimizer::class,
        'RegexParser\\Automata\\DfaState' => \PHPRegex\Automata\Model\DfaState::class,
        'RegexParser\\Automata\\EquivalenceResult' => \PHPRegex\Automata\Solver\EquivalenceResult::class,
        'RegexParser\\Automata\\HopcroftWorklist' => \PHPRegex\Automata\Minimization\HopcroftWorklist::class,
        'RegexParser\\Automata\\IntersectionResult' => \PHPRegex\Automata\Solver\IntersectionResult::class,
        'RegexParser\\Automata\\MatchMode' => \PHPRegex\Automata\Options\MatchMode::class,
        'RegexParser\\Automata\\MinimizationAlgorithm' => \PHPRegex\Automata\Minimization\MinimizationAlgorithm::class,
        'RegexParser\\Automata\\MinimizationAlgorithmFactory' => \PHPRegex\Automata\Minimization\MinimizationAlgorithmFactory::class,
        'RegexParser\\Automata\\MinimizationAlgorithmInterface' => \PHPRegex\Automata\Minimization\MinimizationAlgorithmInterface::class,
        'RegexParser\\Automata\\Minimization\\DfaMinimizer' => \PHPRegex\Automata\Minimization\DfaMinimizer::class,
        'RegexParser\\Automata\\Minimization\\HopcroftWorklist' => \PHPRegex\Automata\Minimization\HopcroftWorklist::class,
        'RegexParser\\Automata\\Minimization\\MinimizationAlgorithm' => \PHPRegex\Automata\Minimization\MinimizationAlgorithm::class,
        'RegexParser\\Automata\\Minimization\\MinimizationAlgorithmFactory' => \PHPRegex\Automata\Minimization\MinimizationAlgorithmFactory::class,
        'RegexParser\\Automata\\Minimization\\MinimizationAlgorithmInterface' => \PHPRegex\Automata\Minimization\MinimizationAlgorithmInterface::class,
        'RegexParser\\Automata\\Minimization\\MoorePartitionRefinement' => \PHPRegex\Automata\Minimization\MoorePartitionRefinement::class,
        'RegexParser\\Automata\\Minimization\\WorkBudgetAwareMinimizationAlgorithmInterface' => \PHPRegex\Automata\Minimization\WorkBudgetAwareMinimizationAlgorithmInterface::class,
        'RegexParser\\Automata\\Model\\Dfa' => \PHPRegex\Automata\Model\Dfa::class,
        'RegexParser\\Automata\\Model\\DfaState' => \PHPRegex\Automata\Model\DfaState::class,
        'RegexParser\\Automata\\Model\\Nfa' => \PHPRegex\Automata\Model\Nfa::class,
        'RegexParser\\Automata\\Model\\NfaFragment' => \PHPRegex\Automata\Model\NfaFragment::class,
        'RegexParser\\Automata\\Model\\NfaState' => \PHPRegex\Automata\Model\NfaState::class,
        'RegexParser\\Automata\\Model\\NfaTransition' => \PHPRegex\Automata\Model\NfaTransition::class,
        'RegexParser\\Automata\\MoorePartitionRefinement' => \PHPRegex\Automata\Minimization\MoorePartitionRefinement::class,
        'RegexParser\\Automata\\Nfa' => \PHPRegex\Automata\Model\Nfa::class,
        'RegexParser\\Automata\\NfaBuilder' => \PHPRegex\Automata\Builder\NfaBuilder::class,
        'RegexParser\\Automata\\NfaFragment' => \PHPRegex\Automata\Model\NfaFragment::class,
        'RegexParser\\Automata\\NfaState' => \PHPRegex\Automata\Model\NfaState::class,
        'RegexParser\\Automata\\NfaTransition' => \PHPRegex\Automata\Model\NfaTransition::class,
        'RegexParser\\Automata\\Options\\MatchMode' => \PHPRegex\Automata\Options\MatchMode::class,
        'RegexParser\\Automata\\Options\\SolverOptions' => \PHPRegex\Automata\Options\SolverOptions::class,
        'RegexParser\\Automata\\RegexSolver' => \PHPRegex\Automata\LanguageSolver::class,
        'RegexParser\\Automata\\RegularSubsetValidator' => \PHPRegex\Automata\Transform\RegularSubsetValidator::class,
        'RegexParser\\Automata\\SolverOptions' => \PHPRegex\Automata\Options\SolverOptions::class,
        'RegexParser\\Automata\\Solver\\DfaCacheInterface' => \PHPRegex\Automata\Solver\DfaCacheInterface::class,
        'RegexParser\\Automata\\Solver\\EquivalenceResult' => \PHPRegex\Automata\Solver\EquivalenceResult::class,
        'RegexParser\\Automata\\Solver\\InMemoryDfaCache' => \PHPRegex\Automata\Solver\InMemoryDfaCache::class,
        'RegexParser\\Automata\\Solver\\IntersectionResult' => \PHPRegex\Automata\Solver\IntersectionResult::class,
        'RegexParser\\Automata\\Solver\\RegexSolver' => \PHPRegex\Automata\LanguageSolver::class,
        'RegexParser\\Automata\\Solver\\SubsetResult' => \PHPRegex\Automata\Solver\SubsetResult::class,
        'RegexParser\\Automata\\SubsetResult' => \PHPRegex\Automata\Solver\SubsetResult::class,
        'RegexParser\\Automata\\Support\\WorkBudget' => \PHPRegex\Automata\Support\WorkBudget::class,
        'RegexParser\\Automata\\Transform\\AstToNfaTransformer' => \PHPRegex\Automata\Transform\AstToNfaTransformer::class,
        'RegexParser\\Automata\\Transform\\AstToNfaTransformerInterface' => \PHPRegex\Automata\Transform\AstToNfaTransformerInterface::class,
        'RegexParser\\Automata\\Transform\\RegularSubsetValidator' => \PHPRegex\Automata\Transform\RegularSubsetValidator::class,
        'RegexParser\\Automata\\Unicode\\CodePointHelper' => \PHPRegex\Automata\Unicode\CodePointHelper::class,
        'RegexParser\\Bridge\\PHPStan\\RegexParserRule' => \PHPRegex\PHPStan\RegexPatternRule::class,
        'RegexParser\\Bridge\\Symfony\\Analyzer\\AnalysisContext' => \PHPRegex\Symfony\Analyzer\AnalysisContext::class,
        'RegexParser\\Bridge\\Symfony\\Analyzer\\AnalysisIssue' => \PHPRegex\Symfony\Analyzer\AnalysisIssue::class,
        'RegexParser\\Bridge\\Symfony\\Analyzer\\AnalysisNotice' => \PHPRegex\Symfony\Analyzer\AnalysisNotice::class,
        'RegexParser\\Bridge\\Symfony\\Analyzer\\AnalysisReport' => \PHPRegex\Symfony\Analyzer\SecurityReport::class,
        'RegexParser\\Bridge\\Symfony\\Analyzer\\AnalyzerInterface' => \PHPRegex\Symfony\Analyzer\AnalyzerInterface::class,
        'RegexParser\\Bridge\\Symfony\\Analyzer\\AnalyzerRegistry' => \PHPRegex\Symfony\Analyzer\AnalyzerRegistry::class,
        'RegexParser\\Bridge\\Symfony\\Analyzer\\Formatter\\ConsoleReportFormatter' => \PHPRegex\Symfony\Analyzer\Formatter\ConsoleReportFormatter::class,
        'RegexParser\\Bridge\\Symfony\\Analyzer\\Formatter\\JsonReportFormatter' => \PHPRegex\Symfony\Analyzer\Formatter\JsonReportFormatter::class,
        'RegexParser\\Bridge\\Symfony\\Analyzer\\IssueDetail' => \PHPRegex\Symfony\Analyzer\IssueDetail::class,
        'RegexParser\\Bridge\\Symfony\\Analyzer\\ReportSection' => \PHPRegex\Symfony\Analyzer\ReportSection::class,
        'RegexParser\\Bridge\\Symfony\\Analyzer\\RoutesAnalyzer' => \PHPRegex\Symfony\Analyzer\RoutesAnalyzer::class,
        'RegexParser\\Bridge\\Symfony\\Analyzer\\SecurityAnalyzer' => \PHPRegex\Symfony\Analyzer\SecurityAnalyzer::class,
        'RegexParser\\Bridge\\Symfony\\Analyzer\\Severity' => \PHPRegex\Symfony\Analyzer\CheckOutcome::class,
        'RegexParser\\Bridge\\Symfony\\Command\\CompareCommand' => \PHPRegex\Symfony\Command\CompareCommand::class,
        'RegexParser\\Bridge\\Symfony\\Command\\RegexAnalyzeCommand' => \PHPRegex\Symfony\Command\AnalyzeCommand::class,
        'RegexParser\\Bridge\\Symfony\\Command\\RegexLintCommand' => \PHPRegex\Symfony\Command\LintCommand::class,
        'RegexParser\\Bridge\\Symfony\\Command\\RegexRoutesCommand' => \PHPRegex\Symfony\Command\RoutesCommand::class,
        'RegexParser\\Bridge\\Symfony\\Command\\RegexSecurityCommand' => \PHPRegex\Symfony\Command\SecurityCommand::class,
        'RegexParser\\Bridge\\Symfony\\Command\\RegexTranspileCommand' => \PHPRegex\Symfony\Command\TranspileCommand::class,
        'RegexParser\\Bridge\\Symfony\\DependencyInjection\\Configuration' => \PHPRegex\Symfony\DependencyInjection\Configuration::class,
        'RegexParser\\Bridge\\Symfony\\DependencyInjection\\RegexParserExtension' => \PHPRegex\Symfony\DependencyInjection\PHPRegexExtension::class,
        'RegexParser\\Bridge\\Symfony\\Extractor\\RouteRegexPatternSource' => \PHPRegex\Symfony\Extractor\RoutePatternSource::class,
        'RegexParser\\Bridge\\Symfony\\Extractor\\ValidatorRegexPatternSource' => \PHPRegex\Symfony\Extractor\ValidatorPatternSource::class,
        'RegexParser\\Bridge\\Symfony\\Output\\SymfonyConsoleFormatter' => \PHPRegex\Symfony\Output\SymfonyConsoleFormatter::class,
        'RegexParser\\Bridge\\Symfony\\RegexParserBundle' => \PHPRegex\Symfony\PHPRegexBundle::class,
        'RegexParser\\Bridge\\Symfony\\Routing\\RouteConflictAnalyzer' => \PHPRegex\Symfony\Routing\RouteConflictAnalyzer::class,
        'RegexParser\\Bridge\\Symfony\\Routing\\RouteConflictReport' => \PHPRegex\Symfony\Routing\RouteConflictReport::class,
        'RegexParser\\Bridge\\Symfony\\Routing\\RouteConflictSuggestionBuilder' => \PHPRegex\Symfony\Routing\RouteConflictSuggestionBuilder::class,
        'RegexParser\\Bridge\\Symfony\\Routing\\RouteControllerFileResolver' => \PHPRegex\Symfony\Routing\RouteControllerFileResolver::class,
        'RegexParser\\Bridge\\Symfony\\Routing\\RouteRequirementNormalizer' => \PHPRegex\Symfony\Routing\RouteRequirementNormalizer::class,
        'RegexParser\\Bridge\\Symfony\\Security\\SecurityAccessControlAnalyzer' => \PHPRegex\Symfony\Security\SecurityAccessControlAnalyzer::class,
        'RegexParser\\Bridge\\Symfony\\Security\\SecurityAccessControlReport' => \PHPRegex\Symfony\Security\SecurityAccessControlReport::class,
        'RegexParser\\Bridge\\Symfony\\Security\\SecurityAccessSuggestionBuilder' => \PHPRegex\Symfony\Security\SecurityAccessSuggestionBuilder::class,
        'RegexParser\\Bridge\\Symfony\\Security\\SecurityConfigExtractor' => \PHPRegex\Symfony\Security\SecurityConfigExtractor::class,
        'RegexParser\\Bridge\\Symfony\\Security\\SecurityConfigLocator' => \PHPRegex\Symfony\Security\SecurityConfigLocator::class,
        'RegexParser\\Bridge\\Symfony\\Security\\SecurityFirewallAnalyzer' => \PHPRegex\Symfony\Security\SecurityFirewallAnalyzer::class,
        'RegexParser\\Bridge\\Symfony\\Security\\SecurityFirewallReport' => \PHPRegex\Symfony\Security\SecurityFirewallReport::class,
        'RegexParser\\Bridge\\Symfony\\Security\\SecurityPatternNormalizer' => \PHPRegex\Symfony\Security\SecurityPatternNormalizer::class,
        'RegexParser\\Cache\\ArrayCache' => \PHPRegex\Parser\Cache\ArrayCache::class,
        'RegexParser\\Cache\\CacheInterface' => \PHPRegex\Parser\Cache\CacheInterface::class,
        'RegexParser\\Cache\\FilesystemCache' => \PHPRegex\Parser\Cache\FilesystemCache::class,
        'RegexParser\\Cache\\NullCache' => \PHPRegex\Parser\Cache\NullCache::class,
        'RegexParser\\Cache\\PsrCacheAdapter' => \PHPRegex\Parser\Cache\PsrCacheAdapter::class,
        'RegexParser\\Cache\\PsrSimpleCacheAdapter' => \PHPRegex\Parser\Cache\PsrSimpleCacheAdapter::class,
        'RegexParser\\Cache\\RemovableCacheInterface' => \PHPRegex\Parser\Cache\RemovableCacheInterface::class,
        'RegexParser\\Cli\\Application' => \PHPRegex\Cli\Application::class,
        'RegexParser\\Cli\\Command\\AbstractCommand' => \PHPRegex\Cli\Command\AbstractCommand::class,
        'RegexParser\\Cli\\Command\\AnalyzeCommand' => \PHPRegex\Cli\Command\AnalyzeCommand::class,
        'RegexParser\\Cli\\Command\\ClearCacheCommand' => \PHPRegex\Cli\Command\ClearCacheCommand::class,
        'RegexParser\\Cli\\Command\\CommandInterface' => \PHPRegex\Cli\Command\CommandInterface::class,
        'RegexParser\\Cli\\Command\\CompareCommand' => \PHPRegex\Cli\Command\CompareCommand::class,
        'RegexParser\\Cli\\Command\\DebugCommand' => \PHPRegex\Cli\Command\DebugCommand::class,
        'RegexParser\\Cli\\Command\\DiagramCommand' => \PHPRegex\Cli\Command\DiagramCommand::class,
        'RegexParser\\Cli\\Command\\ExplainCommand' => \PHPRegex\Cli\Command\ExplainCommand::class,
        'RegexParser\\Cli\\Command\\GraphCommand' => \PHPRegex\Cli\Command\GraphCommand::class,
        'RegexParser\\Cli\\Command\\HelpCommand' => \PHPRegex\Cli\Command\HelpCommand::class,
        'RegexParser\\Cli\\Command\\HighlightCommand' => \PHPRegex\Cli\Command\HighlightCommand::class,
        'RegexParser\\Cli\\Command\\ParseCommand' => \PHPRegex\Cli\Command\ParseCommand::class,
        'RegexParser\\Cli\\Command\\RedosCommand' => \PHPRegex\Cli\Command\RedosCommand::class,
        'RegexParser\\Cli\\Command\\SelfUpdateCommand' => \PHPRegex\Cli\Command\SelfUpdateCommand::class,
        'RegexParser\\Cli\\Command\\TranspileCommand' => \PHPRegex\Cli\Command\TranspileCommand::class,
        'RegexParser\\Cli\\Command\\ValidateCommand' => \PHPRegex\Cli\Command\ValidateCommand::class,
        'RegexParser\\Cli\\Command\\VersionCommand' => \PHPRegex\Cli\Command\VersionCommand::class,
        'RegexParser\\Cli\\ConsoleStyle' => \PHPRegex\Cli\ConsoleStyle::class,
        'RegexParser\\Cli\\GlobalOptions' => \PHPRegex\Cli\GlobalOptions::class,
        'RegexParser\\Cli\\GlobalOptionsParser' => \PHPRegex\Cli\GlobalOptionsParser::class,
        'RegexParser\\Cli\\Graph\\GraphGenerator' => \PHPRegex\Cli\Graph\GraphGenerator::class,
        'RegexParser\\Cli\\Graph\\GraphvizDumper' => \PHPRegex\Cli\Graph\GraphvizDumper::class,
        'RegexParser\\Cli\\Graph\\MermaidDumper' => \PHPRegex\Cli\Graph\MermaidDumper::class,
        'RegexParser\\Cli\\Input' => \PHPRegex\Cli\Input::class,
        'RegexParser\\Cli\\Output' => \PHPRegex\Cli\Output::class,
        'RegexParser\\Cli\\ParsedGlobalOptions' => \PHPRegex\Cli\ParsedGlobalOptions::class,
        'RegexParser\\Cli\\SelfUpdate\\SelfUpdater' => \PHPRegex\Cli\SelfUpdate\SelfUpdater::class,
        'RegexParser\\Exception\\ComplexityException' => \PHPRegex\Automata\Exception\ComplexityException::class,
        'RegexParser\\Exception\\InvalidRegexOptionException' => \PHPRegex\Parser\Exception\InvalidRegexOptionException::class,
        'RegexParser\\Exception\\LexerException' => \PHPRegex\Parser\Exception\LexerException::class,
        'RegexParser\\Exception\\ParserException' => \PHPRegex\Parser\Exception\ParserException::class,
        'RegexParser\\Exception\\RecursionLimitException' => \PHPRegex\Parser\Exception\RecursionLimitException::class,
        'RegexParser\\Exception\\RegexException' => \PHPRegex\Parser\Exception\RegexException::class,
        'RegexParser\\Exception\\RegexParserExceptionInterface' => \PHPRegex\Parser\Exception\ExceptionInterface::class,
        'RegexParser\\Exception\\ResourceLimitException' => \PHPRegex\Parser\Exception\ResourceLimitException::class,
        'RegexParser\\Exception\\SemanticErrorException' => \PHPRegex\Parser\Exception\SemanticErrorException::class,
        'RegexParser\\Exception\\SyntaxErrorException' => \PHPRegex\Parser\Exception\SyntaxErrorException::class,
        'RegexParser\\Exception\\TranspileException' => \PHPRegex\Transpiler\TranspileException::class,
        'RegexParser\\Exception\\VisualContextTrait' => \PHPRegex\Parser\Exception\VisualContextTrait::class,
        'RegexParser\\GroupNumbering' => \PHPRegex\Parser\Analysis\GroupNumbering::class,
        'RegexParser\\GroupNumberingCollector' => \PHPRegex\Parser\Analysis\GroupNumberingCollector::class,
        'RegexParser\\Internal\\PatternParser' => \PHPRegex\Parser\Internal\PatternParser::class,
        'RegexParser\\Lexer' => \PHPRegex\Parser\Lexer::class,
        'RegexParser\\LintIssue' => \PHPRegex\Linter\Rule\RuleViolation::class,
        'RegexParser\\Lint\\Command\\LintArgumentParser' => \PHPRegex\Linter\Config\LintArgumentParser::class,
        'RegexParser\\Lint\\Command\\LintArguments' => \PHPRegex\Linter\Config\LintArguments::class,
        'RegexParser\\Lint\\Command\\LintCommand' => \PHPRegex\Cli\Command\LintCommand::class,
        'RegexParser\\Lint\\Command\\LintConfigLoader' => \PHPRegex\Linter\Config\LintConfigLoader::class,
        'RegexParser\\Lint\\Command\\LintConfigResult' => \PHPRegex\Linter\Config\LintConfigResult::class,
        'RegexParser\\Lint\\Command\\LintDefaultsBuilder' => \PHPRegex\Linter\Config\LintDefaultsBuilder::class,
        'RegexParser\\Lint\\Command\\LintExtractorFactory' => \PHPRegex\Linter\Config\LintExtractorFactory::class,
        'RegexParser\\Lint\\Command\\LintOutputRenderer' => \PHPRegex\Cli\Command\LintOutputRenderer::class,
        'RegexParser\\Lint\\Command\\LintParseResult' => \PHPRegex\Linter\Config\LintParseResult::class,
        'RegexParser\\Lint\\ExtractorInterface' => \PHPRegex\Linter\Extraction\ExtractorInterface::class,
        'RegexParser\\Lint\\Formatter\\AbstractOutputFormatter' => \PHPRegex\Linter\Formatter\AbstractOutputFormatter::class,
        'RegexParser\\Lint\\Formatter\\CheckstyleFormatter' => \PHPRegex\Linter\Formatter\CheckstyleFormatter::class,
        'RegexParser\\Lint\\Formatter\\ConsoleFormatter' => \PHPRegex\Linter\Formatter\ConsoleFormatter::class,
        'RegexParser\\Lint\\Formatter\\FormatterRegistry' => \PHPRegex\Linter\Formatter\FormatterRegistry::class,
        'RegexParser\\Lint\\Formatter\\GithubFormatter' => \PHPRegex\Linter\Formatter\GithubFormatter::class,
        'RegexParser\\Lint\\Formatter\\JsonFormatter' => \PHPRegex\Linter\Formatter\JsonFormatter::class,
        'RegexParser\\Lint\\Formatter\\JunitFormatter' => \PHPRegex\Linter\Formatter\JunitFormatter::class,
        'RegexParser\\Lint\\Formatter\\LinkFormatter' => \PHPRegex\Linter\Formatter\LinkFormatter::class,
        'RegexParser\\Lint\\Formatter\\OutputConfiguration' => \PHPRegex\Linter\Formatter\OutputConfiguration::class,
        'RegexParser\\Lint\\Formatter\\OutputFormatterInterface' => \PHPRegex\Linter\Formatter\OutputFormatterInterface::class,
        'RegexParser\\Lint\\Formatter\\RelativePathHelper' => \PHPRegex\Linter\Formatter\RelativePathHelper::class,
        'RegexParser\\Lint\\PhpRegexPatternSource' => \PHPRegex\Linter\Source\PhpFilePatternSource::class,
        'RegexParser\\Lint\\PhpStanExtractionStrategy' => \PHPRegex\Linter\Extraction\PhpParserExtractionStrategy::class,
        'RegexParser\\Lint\\RegexAnalysisService' => \PHPRegex\Linter\AnalysisService::class,
        'RegexParser\\Lint\\RegexLintReport' => \PHPRegex\Linter\LintReport::class,
        'RegexParser\\Lint\\RegexLintRequest' => \PHPRegex\Linter\LintRequest::class,
        'RegexParser\\Lint\\RegexLintService' => \PHPRegex\Linter\LintService::class,
        'RegexParser\\Lint\\RegexPatternExtractor' => \PHPRegex\Linter\PatternExtractor::class,
        'RegexParser\\Lint\\RegexPatternOccurrence' => \PHPRegex\Linter\PatternOccurrence::class,
        'RegexParser\\Lint\\RegexPatternSourceCollection' => \PHPRegex\Linter\Source\PatternSourceCollection::class,
        'RegexParser\\Lint\\RegexPatternSourceContext' => \PHPRegex\Linter\Source\PatternSourceContext::class,
        'RegexParser\\Lint\\RegexPatternSourceInterface' => \PHPRegex\Linter\Source\PatternSourceInterface::class,
        'RegexParser\\Lint\\TokenBasedExtractionStrategy' => \PHPRegex\Linter\Extraction\TokenBasedExtractionStrategy::class,
        'RegexParser\\LiteralExtractionResult' => \PHPRegex\Parser\Analysis\LiteralExtractionResult::class,
        'RegexParser\\LiteralSet' => \PHPRegex\Parser\Analysis\LiteralSet::class,
        'RegexParser\\NodeVisitor\\AbstractNodeVisitor' => \PHPRegex\Parser\AbstractNodeVisitor::class,
        'RegexParser\\NodeVisitor\\AsciiTreeVisitor' => \PHPRegex\Explain\AsciiTreeRenderer::class,
        'RegexParser\\NodeVisitor\\CompilerNodeVisitor' => \PHPRegex\Parser\Printer\PatternPrinter::class,
        'RegexParser\\NodeVisitor\\ComplexityScoreNodeVisitor' => \PHPRegex\Parser\Analysis\ComplexityScorer::class,
        'RegexParser\\NodeVisitor\\ConsoleHighlighterVisitor' => \PHPRegex\Explain\Highlighter\ConsoleHighlighter::class,
        'RegexParser\\NodeVisitor\\DumperNodeVisitor' => \PHPRegex\Parser\Printer\NodeDumper::class,
        'RegexParser\\NodeVisitor\\ExplainNodeVisitor' => \PHPRegex\Explain\TextExplainer::class,
        'RegexParser\\NodeVisitor\\HighlighterVisitor' => \PHPRegex\Explain\Highlighter\AbstractHighlighter::class,
        'RegexParser\\NodeVisitor\\HtmlExplainNodeVisitor' => \PHPRegex\Explain\HtmlExplainer::class,
        'RegexParser\\NodeVisitor\\HtmlHighlighterVisitor' => \PHPRegex\Explain\Highlighter\HtmlHighlighter::class,
        'RegexParser\\NodeVisitor\\LengthRangeNodeVisitor' => \PHPRegex\Parser\Analysis\LengthRangeCalculator::class,
        'RegexParser\\NodeVisitor\\LinterNodeVisitor' => \PHPRegex\Linter\PatternLinter::class,
        'RegexParser\\NodeVisitor\\LiteralExtractorNodeVisitor' => \PHPRegex\Parser\Analysis\LiteralExtractor::class,
        'RegexParser\\NodeVisitor\\MermaidNodeVisitor' => \PHPRegex\Explain\MermaidRenderer::class,
        'RegexParser\\NodeVisitor\\MetricsNodeVisitor' => \PHPRegex\Parser\Analysis\MetricsCollector::class,
        'RegexParser\\NodeVisitor\\ModernizerNodeVisitor' => \PHPRegex\Optimizer\Modernizer::class,
        'RegexParser\\NodeVisitor\\NodeVisitorInterface' => \PHPRegex\Parser\NodeVisitorInterface::class,
        'RegexParser\\NodeVisitor\\OptimizerNodeVisitor' => \PHPRegex\Optimizer\Rewriter::class,
        'RegexParser\\NodeVisitor\\RailroadSvgVisitor' => \PHPRegex\Explain\RailroadSvgRenderer::class,
        'RegexParser\\NodeVisitor\\ReDoSProfileNodeVisitor' => \PHPRegex\Redos\RedosProfiler::class,
        'RegexParser\\NodeVisitor\\SampleGeneratorNodeVisitor' => \PHPRegex\Generator\SampleGenerator::class,
        'RegexParser\\NodeVisitor\\TestCaseGeneratorNodeVisitor' => \PHPRegex\Generator\TestCaseGenerator::class,
        'RegexParser\\NodeVisitor\\ValidatorNodeVisitor' => \PHPRegex\Parser\Validation\Validator::class,
        'RegexParser\\Node\\AbstractNode' => \PHPRegex\Parser\Node\AbstractNode::class,
        'RegexParser\\Node\\AlternationNode' => \PHPRegex\Parser\Node\AlternationNode::class,
        'RegexParser\\Node\\AnchorNode' => \PHPRegex\Parser\Node\AnchorNode::class,
        'RegexParser\\Node\\AssertionNode' => \PHPRegex\Parser\Node\AssertionNode::class,
        'RegexParser\\Node\\BackrefNode' => \PHPRegex\Parser\Node\BackrefNode::class,
        'RegexParser\\Node\\CalloutNode' => \PHPRegex\Parser\Node\CalloutNode::class,
        'RegexParser\\Node\\CharClassNode' => \PHPRegex\Parser\Node\CharClassNode::class,
        'RegexParser\\Node\\CharLiteralNode' => \PHPRegex\Parser\Node\CharLiteralNode::class,
        'RegexParser\\Node\\CharLiteralType' => \PHPRegex\Parser\Node\CharLiteralType::class,
        'RegexParser\\Node\\CharTypeNode' => \PHPRegex\Parser\Node\CharTypeNode::class,
        'RegexParser\\Node\\CommentNode' => \PHPRegex\Parser\Node\CommentNode::class,
        'RegexParser\\Node\\ConditionalNode' => \PHPRegex\Parser\Node\ConditionalNode::class,
        'RegexParser\\Node\\ControlCharNode' => \PHPRegex\Parser\Node\ControlCharNode::class,
        'RegexParser\\Node\\DefineNode' => \PHPRegex\Parser\Node\DefineNode::class,
        'RegexParser\\Node\\DotNode' => \PHPRegex\Parser\Node\DotNode::class,
        'RegexParser\\Node\\GroupNode' => \PHPRegex\Parser\Node\GroupNode::class,
        'RegexParser\\Node\\GroupType' => \PHPRegex\Parser\Node\GroupType::class,
        'RegexParser\\Node\\KeepNode' => \PHPRegex\Parser\Node\KeepNode::class,
        'RegexParser\\Node\\LimitMatchNode' => \PHPRegex\Parser\Node\LimitMatchNode::class,
        'RegexParser\\Node\\LiteralNode' => \PHPRegex\Parser\Node\LiteralNode::class,
        'RegexParser\\Node\\NodeInterface' => \PHPRegex\Parser\Node\NodeInterface::class,
        'RegexParser\\Node\\PcreVerbNode' => \PHPRegex\Parser\Node\PcreVerbNode::class,
        'RegexParser\\Node\\PosixClassNode' => \PHPRegex\Parser\Node\PosixClassNode::class,
        'RegexParser\\Node\\QuantifierNode' => \PHPRegex\Parser\Node\QuantifierNode::class,
        'RegexParser\\Node\\QuantifierType' => \PHPRegex\Parser\Node\QuantifierType::class,
        'RegexParser\\Node\\RangeNode' => \PHPRegex\Parser\Node\RangeNode::class,
        'RegexParser\\Node\\RegexNode' => \PHPRegex\Parser\Node\RegexNode::class,
        'RegexParser\\Node\\ScriptRunNode' => \PHPRegex\Parser\Node\ScriptRunNode::class,
        'RegexParser\\Node\\SequenceNode' => \PHPRegex\Parser\Node\SequenceNode::class,
        'RegexParser\\Node\\SubroutineNode' => \PHPRegex\Parser\Node\SubroutineNode::class,
        'RegexParser\\Node\\UnicodePropNode' => \PHPRegex\Parser\Node\UnicodePropNode::class,
        'RegexParser\\Node\\VersionConditionNode' => \PHPRegex\Parser\Node\VersionConditionNode::class,
        'RegexParser\\OptimizationResult' => \PHPRegex\Optimizer\OptimizationResult::class,
        'RegexParser\\Parser' => \PHPRegex\Parser\Syntax\TokenParser::class,
        'RegexParser\\ProblemType' => \PHPRegex\Linter\DiagnosticType::class,
        'RegexParser\\ReDoS\\CharSet' => \PHPRegex\Parser\Analysis\ByteCharSet::class,
        'RegexParser\\ReDoS\\CharSetAnalyzer' => \PHPRegex\Parser\Analysis\CharSetAnalyzer::class,
        'RegexParser\\ReDoS\\ReDoSAnalysis' => \PHPRegex\Redos\RedosAnalysis::class,
        'RegexParser\\ReDoS\\ReDoSAnalyzer' => \PHPRegex\Redos\RedosAnalyzer::class,
        'RegexParser\\ReDoS\\ReDoSConfidence' => \PHPRegex\Redos\RedosConfidence::class,
        'RegexParser\\ReDoS\\ReDoSConfirmOptions' => \PHPRegex\Redos\ConfirmationOptions::class,
        'RegexParser\\ReDoS\\ReDoSConfirmation' => \PHPRegex\Redos\Confirmation::class,
        'RegexParser\\ReDoS\\ReDoSConfirmationRunner' => \PHPRegex\Redos\ConfirmationRunner::class,
        'RegexParser\\ReDoS\\ReDoSConfirmationRunnerInterface' => \PHPRegex\Redos\ConfirmationRunnerInterface::class,
        'RegexParser\\ReDoS\\ReDoSConfirmationSample' => \PHPRegex\Redos\ConfirmationSample::class,
        'RegexParser\\ReDoS\\ReDoSFinding' => \PHPRegex\Redos\Finding::class,
        'RegexParser\\ReDoS\\ReDoSHeatmap' => \PHPRegex\Redos\Heatmap::class,
        'RegexParser\\ReDoS\\ReDoSHotspot' => \PHPRegex\Redos\Hotspot::class,
        'RegexParser\\ReDoS\\ReDoSInputGenerator' => \PHPRegex\Redos\Internal\InputGenerator::class,
        'RegexParser\\ReDoS\\ReDoSMode' => \PHPRegex\Redos\RedosMode::class,
        'RegexParser\\ReDoS\\ReDoSSeverity' => \PHPRegex\Redos\RedosSeverity::class,
        'RegexParser\\Regex' => \PHPRegex\Toolkit\Regex::class,
        'RegexParser\\RegexOptions' => \PHPRegex\Parser\ParserOptions::class,
        'RegexParser\\RegexPattern' => \PHPRegex\Parser\DelimitedPattern::class,
        'RegexParser\\RegexProblem' => \PHPRegex\Linter\Diagnostic::class,
        'RegexParser\\Runtime\\PcreRuntimeInfo' => \PHPRegex\Cli\PcreRuntimeInfo::class,
        'RegexParser\\Severity' => \PHPRegex\Linter\LintSeverity::class,
        'RegexParser\\Token' => \PHPRegex\Parser\Token\Token::class,
        'RegexParser\\TokenStream' => \PHPRegex\Parser\Token\TokenStream::class,
        'RegexParser\\TokenType' => \PHPRegex\Parser\Token\TokenType::class,
        'RegexParser\\TolerantParseResult' => \PHPRegex\Parser\TolerantParseResult::class,
        'RegexParser\\Transpiler\\RegexTranspiler' => \PHPRegex\Transpiler\Transpiler::class,
        'RegexParser\\Transpiler\\Target\\JavaScript\\JavaScriptCompilerVisitor' => \PHPRegex\Transpiler\Target\JavaScript\JavaScriptPrinter::class,
        'RegexParser\\Transpiler\\Target\\JavaScript\\JavaScriptTarget' => \PHPRegex\Transpiler\Target\JavaScript\JavaScriptTarget::class,
        'RegexParser\\Transpiler\\Target\\Python\\PythonCompilerVisitor' => \PHPRegex\Transpiler\Target\Python\PythonPrinter::class,
        'RegexParser\\Transpiler\\Target\\Python\\PythonTarget' => \PHPRegex\Transpiler\Target\Python\PythonTarget::class,
        'RegexParser\\Transpiler\\Target\\TargetRegistry' => \PHPRegex\Transpiler\Target\TargetRegistry::class,
        'RegexParser\\Transpiler\\Target\\TranspileTargetInterface' => \PHPRegex\Transpiler\Target\TargetInterface::class,
        'RegexParser\\Transpiler\\TranspileContext' => \PHPRegex\Transpiler\TranspileContext::class,
        'RegexParser\\Transpiler\\TranspileOptions' => \PHPRegex\Transpiler\TranspileOptions::class,
        'RegexParser\\Transpiler\\TranspileResult' => \PHPRegex\Transpiler\TranspileResult::class,
        'RegexParser\\ValidationErrorCategory' => \PHPRegex\Parser\Validation\ValidationErrorCategory::class,
        'RegexParser\\ValidationResult' => \PHPRegex\Parser\Validation\ValidationResult::class,
    ];

    /**
     * A 1.3 class gone in 2.0 => what to use instead.
     */
    public const REMOVED = [
        'RegexParser\\Automata\\RegexSolverInterface' => 'type against PHPRegex\\Automata\\LanguageSolver',
        'RegexParser\\Automata\\Solver\\RegexSolverCompilerInterface' => 'type against PHPRegex\\Automata\\LanguageSolver',
        'RegexParser\\Automata\\Solver\\RegexSolverInterface' => 'type against PHPRegex\\Automata\\LanguageSolver',
        'RegexParser\\Node\\ClassOperationNode' => 'no replacement: PHP reads "&&" and "--" in a class as members and ranges, so no pattern ever produced it',
        'RegexParser\\Node\\ClassOperationType' => 'no replacement: it only typed ClassOperationNode',
        'RegexParser\\Node\\UnicodeNode' => 'use PHPRegex\\Parser\\Node\\CharLiteralNode, which every \\x{...} and \\u{...} escape already became',
        'RegexParser\\ReDoS\\ReDoSAnalyzerInterface' => 'type against PHPRegex\\Redos\\RedosAnalyzer',
    ];

    /**
     * A 1.3 enum => [1.3 case => 2.0 case].
     */
    public const ENUM_CASES = [
        'RegexParser\\TokenType' => [
            'T_LITERAL' => 'Literal',
            'T_CHAR_TYPE' => 'CharType',
            'T_GROUP_OPEN' => 'GroupOpen',
            'T_GROUP_CLOSE' => 'GroupClose',
            'T_GROUP_MODIFIER_OPEN' => 'GroupModifierOpen',
            'T_CHAR_CLASS_OPEN' => 'CharClassOpen',
            'T_CHAR_CLASS_CLOSE' => 'CharClassClose',
            'T_QUANTIFIER' => 'Quantifier',
            'T_ALTERNATION' => 'Alternation',
            'T_DOT' => 'Dot',
            'T_ANCHOR' => 'Anchor',
            'T_EOF' => 'Eof',
            'T_RANGE' => 'Range',
            'T_NEGATION' => 'Negation',
            'T_BACKREF' => 'Backref',
            'T_UNICODE' => 'Unicode',
            'T_POSIX_CLASS' => 'PosixClass',
            'T_ASSERTION' => 'Assertion',
            'T_UNICODE_PROP' => 'UnicodeProp',
            'T_OCTAL' => 'Octal',
            'T_OCTAL_LEGACY' => 'OctalLegacy',
            'T_COMMENT_OPEN' => 'CommentOpen',
            'T_PCRE_VERB' => 'PcreVerb',
            'T_G_REFERENCE' => 'GReference',
            'T_KEEP' => 'Keep',
            'T_LITERAL_ESCAPED' => 'LiteralEscaped',
            'T_QUOTE_MODE_START' => 'QuoteModeStart',
            'T_QUOTE_MODE_END' => 'QuoteModeEnd',
            'T_CALLOUT' => 'Callout',
            'T_UNICODE_NAMED' => 'UnicodeNamed',
            'T_CONTROL_CHAR' => 'ControlChar',
        ],
        'RegexParser\\Node\\GroupType' => [
            'T_GROUP_CAPTURING' => 'Capturing',
            'T_GROUP_NON_CAPTURING' => 'NonCapturing',
            'T_GROUP_NAMED' => 'Named',
            'T_GROUP_LOOKAHEAD_POSITIVE' => 'LookaheadPositive',
            'T_GROUP_LOOKAHEAD_NEGATIVE' => 'LookaheadNegative',
            'T_GROUP_LOOKBEHIND_POSITIVE' => 'LookbehindPositive',
            'T_GROUP_LOOKBEHIND_NEGATIVE' => 'LookbehindNegative',
            'T_GROUP_INLINE_FLAGS' => 'InlineFlags',
            'T_GROUP_ATOMIC' => 'Atomic',
            'T_GROUP_BRANCH_RESET' => 'BranchReset',
        ],
        'RegexParser\\Node\\QuantifierType' => [
            'T_GREEDY' => 'Greedy',
            'T_LAZY' => 'Lazy',
            'T_POSSESSIVE' => 'Possessive',
        ],
        'RegexParser\\Node\\CharLiteralType' => [
            'UNICODE' => 'Unicode',
            'UNICODE_NAMED' => 'UnicodeNamed',
            'OCTAL' => 'Octal',
            'OCTAL_LEGACY' => 'OctalLegacy',
        ],
        'RegexParser\\ValidationErrorCategory' => [
            'SYNTAX' => 'Syntax',
            'SEMANTIC' => 'Semantic',
            'PCRE_RUNTIME' => 'PcreRuntime',
        ],
        'RegexParser\\ReDoS\\ReDoSSeverity' => [
            'SAFE' => 'Safe',
            'LOW' => 'Low',
            'MEDIUM' => 'Medium',
            'UNKNOWN' => 'Unknown',
            'HIGH' => 'High',
            'CRITICAL' => 'Critical',
        ],
        'RegexParser\\ReDoS\\ReDoSMode' => [
            'OFF' => 'Off',
            'THEORETICAL' => 'Theoretical',
            'CONFIRMED' => 'Confirmed',
        ],
        'RegexParser\\ReDoS\\ReDoSConfidence' => [
            'LOW' => 'Low',
            'MEDIUM' => 'Medium',
            'HIGH' => 'High',
        ],
        'RegexParser\\Automata\\Options\\MatchMode' => [
            'FULL' => 'Full',
            'PARTIAL' => 'Partial',
        ],
        'RegexParser\\Automata\\Minimization\\MinimizationAlgorithm' => [
            'HOPCROFT' => 'Hopcroft',
            'MOORE' => 'Moore',
        ],
        'RegexParser\\Automata\\Determinization\\DeterminizationAlgorithm' => [
            'SUBSET' => 'Subset',
            'SUBSET_INDEXED' => 'SubsetIndexed',
        ],
        'RegexParser\\Bridge\\Symfony\\Analyzer\\Severity' => [
            'PASS' => 'Pass',
            'WARN' => 'Warn',
            'FAIL' => 'Fail',
            'CRITICAL' => 'Critical',
        ],
    ];

    /**
     * [1.3 class, 1.3 method, 2.0 method].
     */
    public const METHODS = [
        ['RegexParser\\Lint\\RegexAnalysisService', 'getRegex', 'getParser'],
        ['RegexParser\\Automata\\Api\\RegexLanguageSolver', 'intersectionEmpty', 'intersection'],
        ['RegexParser\\Automata\\Api\\RegexLanguageSolver', 'prepare', 'compile'],
        ['RegexParser\\Regex', 'clearValidatorCaches', 'clearCaches'],
    ];
}
