<?php

declare(strict_types=1);

/*
 * This file is part of the PHPRegex package.
 *
 * (c) Younes ENNAJI <younes.ennaji.pro@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace PHPRegex\Toolkit\Upgrade;

/**
 * What 1.3 named, and what 2.0 names it: every class 1.3 shipped, its legacy
 * aliases included, the enum cases renamed and the methods renamed. The
 * upgrade guide's tables and the Rector set read it.
 *
 * @internal
 */
final class UpgradeMap
{
    /**
     * A 1.3 class => its 2.0 name.
     */
    public const RENAMED = [
        'RegexParser\\AnalysisReport' => 'PHPRegex\\Toolkit\\AnalysisReport',
        'RegexParser\\Automata\\Alphabet\\CharSet' => 'PHPRegex\\Automata\\Alphabet\\CharSet',
        'RegexParser\\Automata\\Api\\RegexLanguageSolver' => 'PHPRegex\\Automata\\LanguageSolver',
        'RegexParser\\Automata\\AstToNfaTransformer' => 'PHPRegex\\Automata\\Transform\\AstToNfaTransformer',
        'RegexParser\\Automata\\AstToNfaTransformerInterface' => 'PHPRegex\\Automata\\Transform\\AstToNfaTransformerInterface',
        'RegexParser\\Automata\\Builder\\DfaBuilder' => 'PHPRegex\\Automata\\Builder\\DfaBuilder',
        'RegexParser\\Automata\\Builder\\NfaBuilder' => 'PHPRegex\\Automata\\Builder\\NfaBuilder',
        'RegexParser\\Automata\\CharSet' => 'PHPRegex\\Automata\\Alphabet\\CharSet',
        'RegexParser\\Automata\\Determinization\\DeterminizationAlgorithm' => 'PHPRegex\\Automata\\Determinization\\DeterminizationAlgorithm',
        'RegexParser\\Automata\\Determinization\\DeterminizationAlgorithmFactory' => 'PHPRegex\\Automata\\Determinization\\DeterminizationAlgorithmFactory',
        'RegexParser\\Automata\\Determinization\\DeterminizationAlgorithmInterface' => 'PHPRegex\\Automata\\Determinization\\DeterminizationAlgorithmInterface',
        'RegexParser\\Automata\\Determinization\\SubsetConstruction' => 'PHPRegex\\Automata\\Determinization\\SubsetConstruction',
        'RegexParser\\Automata\\Determinization\\SubsetConstructionIndexed' => 'PHPRegex\\Automata\\Determinization\\SubsetConstructionIndexed',
        'RegexParser\\Automata\\Determinization\\WorkBudgetAwareDeterminizationAlgorithmInterface' => 'PHPRegex\\Automata\\Determinization\\WorkBudgetAwareDeterminizationAlgorithmInterface',
        'RegexParser\\Automata\\Dfa' => 'PHPRegex\\Automata\\Model\\Dfa',
        'RegexParser\\Automata\\DfaBuilder' => 'PHPRegex\\Automata\\Builder\\DfaBuilder',
        'RegexParser\\Automata\\DfaMinimizer' => 'PHPRegex\\Automata\\Minimization\\DfaMinimizer',
        'RegexParser\\Automata\\DfaState' => 'PHPRegex\\Automata\\Model\\DfaState',
        'RegexParser\\Automata\\EquivalenceResult' => 'PHPRegex\\Automata\\Solver\\EquivalenceResult',
        'RegexParser\\Automata\\HopcroftWorklist' => 'PHPRegex\\Automata\\Minimization\\HopcroftWorklist',
        'RegexParser\\Automata\\IntersectionResult' => 'PHPRegex\\Automata\\Solver\\IntersectionResult',
        'RegexParser\\Automata\\MatchMode' => 'PHPRegex\\Automata\\Options\\MatchMode',
        'RegexParser\\Automata\\MinimizationAlgorithm' => 'PHPRegex\\Automata\\Minimization\\MinimizationAlgorithm',
        'RegexParser\\Automata\\MinimizationAlgorithmFactory' => 'PHPRegex\\Automata\\Minimization\\MinimizationAlgorithmFactory',
        'RegexParser\\Automata\\MinimizationAlgorithmInterface' => 'PHPRegex\\Automata\\Minimization\\MinimizationAlgorithmInterface',
        'RegexParser\\Automata\\Minimization\\DfaMinimizer' => 'PHPRegex\\Automata\\Minimization\\DfaMinimizer',
        'RegexParser\\Automata\\Minimization\\HopcroftWorklist' => 'PHPRegex\\Automata\\Minimization\\HopcroftWorklist',
        'RegexParser\\Automata\\Minimization\\MinimizationAlgorithm' => 'PHPRegex\\Automata\\Minimization\\MinimizationAlgorithm',
        'RegexParser\\Automata\\Minimization\\MinimizationAlgorithmFactory' => 'PHPRegex\\Automata\\Minimization\\MinimizationAlgorithmFactory',
        'RegexParser\\Automata\\Minimization\\MinimizationAlgorithmInterface' => 'PHPRegex\\Automata\\Minimization\\MinimizationAlgorithmInterface',
        'RegexParser\\Automata\\Minimization\\MoorePartitionRefinement' => 'PHPRegex\\Automata\\Minimization\\MoorePartitionRefinement',
        'RegexParser\\Automata\\Minimization\\WorkBudgetAwareMinimizationAlgorithmInterface' => 'PHPRegex\\Automata\\Minimization\\WorkBudgetAwareMinimizationAlgorithmInterface',
        'RegexParser\\Automata\\Model\\Dfa' => 'PHPRegex\\Automata\\Model\\Dfa',
        'RegexParser\\Automata\\Model\\DfaState' => 'PHPRegex\\Automata\\Model\\DfaState',
        'RegexParser\\Automata\\Model\\Nfa' => 'PHPRegex\\Automata\\Model\\Nfa',
        'RegexParser\\Automata\\Model\\NfaFragment' => 'PHPRegex\\Automata\\Model\\NfaFragment',
        'RegexParser\\Automata\\Model\\NfaState' => 'PHPRegex\\Automata\\Model\\NfaState',
        'RegexParser\\Automata\\Model\\NfaTransition' => 'PHPRegex\\Automata\\Model\\NfaTransition',
        'RegexParser\\Automata\\MoorePartitionRefinement' => 'PHPRegex\\Automata\\Minimization\\MoorePartitionRefinement',
        'RegexParser\\Automata\\Nfa' => 'PHPRegex\\Automata\\Model\\Nfa',
        'RegexParser\\Automata\\NfaBuilder' => 'PHPRegex\\Automata\\Builder\\NfaBuilder',
        'RegexParser\\Automata\\NfaFragment' => 'PHPRegex\\Automata\\Model\\NfaFragment',
        'RegexParser\\Automata\\NfaState' => 'PHPRegex\\Automata\\Model\\NfaState',
        'RegexParser\\Automata\\NfaTransition' => 'PHPRegex\\Automata\\Model\\NfaTransition',
        'RegexParser\\Automata\\Options\\MatchMode' => 'PHPRegex\\Automata\\Options\\MatchMode',
        'RegexParser\\Automata\\Options\\SolverOptions' => 'PHPRegex\\Automata\\Options\\SolverOptions',
        'RegexParser\\Automata\\RegexSolver' => 'PHPRegex\\Automata\\LanguageSolver',
        'RegexParser\\Automata\\RegularSubsetValidator' => 'PHPRegex\\Automata\\Transform\\RegularSubsetValidator',
        'RegexParser\\Automata\\SolverOptions' => 'PHPRegex\\Automata\\Options\\SolverOptions',
        'RegexParser\\Automata\\Solver\\DfaCacheInterface' => 'PHPRegex\\Automata\\Solver\\DfaCacheInterface',
        'RegexParser\\Automata\\Solver\\EquivalenceResult' => 'PHPRegex\\Automata\\Solver\\EquivalenceResult',
        'RegexParser\\Automata\\Solver\\InMemoryDfaCache' => 'PHPRegex\\Automata\\Solver\\InMemoryDfaCache',
        'RegexParser\\Automata\\Solver\\IntersectionResult' => 'PHPRegex\\Automata\\Solver\\IntersectionResult',
        'RegexParser\\Automata\\Solver\\RegexSolver' => 'PHPRegex\\Automata\\LanguageSolver',
        'RegexParser\\Automata\\Solver\\SubsetResult' => 'PHPRegex\\Automata\\Solver\\SubsetResult',
        'RegexParser\\Automata\\SubsetResult' => 'PHPRegex\\Automata\\Solver\\SubsetResult',
        'RegexParser\\Automata\\Support\\WorkBudget' => 'PHPRegex\\Automata\\Support\\WorkBudget',
        'RegexParser\\Automata\\Transform\\AstToNfaTransformer' => 'PHPRegex\\Automata\\Transform\\AstToNfaTransformer',
        'RegexParser\\Automata\\Transform\\AstToNfaTransformerInterface' => 'PHPRegex\\Automata\\Transform\\AstToNfaTransformerInterface',
        'RegexParser\\Automata\\Transform\\RegularSubsetValidator' => 'PHPRegex\\Automata\\Transform\\RegularSubsetValidator',
        'RegexParser\\Automata\\Unicode\\CodePointHelper' => 'PHPRegex\\Automata\\Unicode\\CodePointHelper',
        'RegexParser\\Bridge\\PHPStan\\RegexParserRule' => 'PHPRegex\\PHPStan\\RegexPatternRule',
        'RegexParser\\Bridge\\Symfony\\Analyzer\\AnalysisContext' => 'PHPRegex\\Symfony\\Analyzer\\AnalysisContext',
        'RegexParser\\Bridge\\Symfony\\Analyzer\\AnalysisIssue' => 'PHPRegex\\Symfony\\Analyzer\\AnalysisIssue',
        'RegexParser\\Bridge\\Symfony\\Analyzer\\AnalysisNotice' => 'PHPRegex\\Symfony\\Analyzer\\AnalysisNotice',
        'RegexParser\\Bridge\\Symfony\\Analyzer\\AnalysisReport' => 'PHPRegex\\Symfony\\Analyzer\\SecurityReport',
        'RegexParser\\Bridge\\Symfony\\Analyzer\\AnalyzerInterface' => 'PHPRegex\\Symfony\\Analyzer\\AnalyzerInterface',
        'RegexParser\\Bridge\\Symfony\\Analyzer\\AnalyzerRegistry' => 'PHPRegex\\Symfony\\Analyzer\\AnalyzerRegistry',
        'RegexParser\\Bridge\\Symfony\\Analyzer\\Formatter\\ConsoleReportFormatter' => 'PHPRegex\\Symfony\\Analyzer\\Formatter\\ConsoleReportFormatter',
        'RegexParser\\Bridge\\Symfony\\Analyzer\\Formatter\\JsonReportFormatter' => 'PHPRegex\\Symfony\\Analyzer\\Formatter\\JsonReportFormatter',
        'RegexParser\\Bridge\\Symfony\\Analyzer\\IssueDetail' => 'PHPRegex\\Symfony\\Analyzer\\IssueDetail',
        'RegexParser\\Bridge\\Symfony\\Analyzer\\ReportSection' => 'PHPRegex\\Symfony\\Analyzer\\ReportSection',
        'RegexParser\\Bridge\\Symfony\\Analyzer\\RoutesAnalyzer' => 'PHPRegex\\Symfony\\Analyzer\\RoutesAnalyzer',
        'RegexParser\\Bridge\\Symfony\\Analyzer\\SecurityAnalyzer' => 'PHPRegex\\Symfony\\Analyzer\\SecurityAnalyzer',
        'RegexParser\\Bridge\\Symfony\\Analyzer\\Severity' => 'PHPRegex\\Symfony\\Analyzer\\CheckOutcome',
        'RegexParser\\Bridge\\Symfony\\Command\\CompareCommand' => 'PHPRegex\\Symfony\\Command\\CompareCommand',
        'RegexParser\\Bridge\\Symfony\\Command\\RegexAnalyzeCommand' => 'PHPRegex\\Symfony\\Command\\AnalyzeCommand',
        'RegexParser\\Bridge\\Symfony\\Command\\RegexLintCommand' => 'PHPRegex\\Symfony\\Command\\LintCommand',
        'RegexParser\\Bridge\\Symfony\\Command\\RegexRoutesCommand' => 'PHPRegex\\Symfony\\Command\\RoutesCommand',
        'RegexParser\\Bridge\\Symfony\\Command\\RegexSecurityCommand' => 'PHPRegex\\Symfony\\Command\\SecurityCommand',
        'RegexParser\\Bridge\\Symfony\\Command\\RegexTranspileCommand' => 'PHPRegex\\Symfony\\Command\\TranspileCommand',
        'RegexParser\\Bridge\\Symfony\\DependencyInjection\\Configuration' => 'PHPRegex\\Symfony\\DependencyInjection\\Configuration',
        'RegexParser\\Bridge\\Symfony\\DependencyInjection\\RegexParserExtension' => 'PHPRegex\\Symfony\\DependencyInjection\\PHPRegexExtension',
        'RegexParser\\Bridge\\Symfony\\Extractor\\RouteRegexPatternSource' => 'PHPRegex\\Symfony\\Extractor\\RoutePatternSource',
        'RegexParser\\Bridge\\Symfony\\Extractor\\ValidatorRegexPatternSource' => 'PHPRegex\\Symfony\\Extractor\\ValidatorPatternSource',
        'RegexParser\\Bridge\\Symfony\\Output\\SymfonyConsoleFormatter' => 'PHPRegex\\Symfony\\Output\\SymfonyConsoleFormatter',
        'RegexParser\\Bridge\\Symfony\\RegexParserBundle' => 'PHPRegex\\Symfony\\PHPRegexBundle',
        'RegexParser\\Bridge\\Symfony\\Routing\\RouteConflictAnalyzer' => 'PHPRegex\\Symfony\\Routing\\RouteConflictAnalyzer',
        'RegexParser\\Bridge\\Symfony\\Routing\\RouteConflictReport' => 'PHPRegex\\Symfony\\Routing\\RouteConflictReport',
        'RegexParser\\Bridge\\Symfony\\Routing\\RouteConflictSuggestionBuilder' => 'PHPRegex\\Symfony\\Routing\\RouteConflictSuggestionBuilder',
        'RegexParser\\Bridge\\Symfony\\Routing\\RouteControllerFileResolver' => 'PHPRegex\\Symfony\\Routing\\RouteControllerFileResolver',
        'RegexParser\\Bridge\\Symfony\\Routing\\RouteRequirementNormalizer' => 'PHPRegex\\Symfony\\Routing\\RouteRequirementNormalizer',
        'RegexParser\\Bridge\\Symfony\\Security\\SecurityAccessControlAnalyzer' => 'PHPRegex\\Symfony\\Security\\SecurityAccessControlAnalyzer',
        'RegexParser\\Bridge\\Symfony\\Security\\SecurityAccessControlReport' => 'PHPRegex\\Symfony\\Security\\SecurityAccessControlReport',
        'RegexParser\\Bridge\\Symfony\\Security\\SecurityAccessSuggestionBuilder' => 'PHPRegex\\Symfony\\Security\\SecurityAccessSuggestionBuilder',
        'RegexParser\\Bridge\\Symfony\\Security\\SecurityConfigExtractor' => 'PHPRegex\\Symfony\\Security\\SecurityConfigExtractor',
        'RegexParser\\Bridge\\Symfony\\Security\\SecurityConfigLocator' => 'PHPRegex\\Symfony\\Security\\SecurityConfigLocator',
        'RegexParser\\Bridge\\Symfony\\Security\\SecurityFirewallAnalyzer' => 'PHPRegex\\Symfony\\Security\\SecurityFirewallAnalyzer',
        'RegexParser\\Bridge\\Symfony\\Security\\SecurityFirewallReport' => 'PHPRegex\\Symfony\\Security\\SecurityFirewallReport',
        'RegexParser\\Bridge\\Symfony\\Security\\SecurityPatternNormalizer' => 'PHPRegex\\Symfony\\Security\\SecurityPatternNormalizer',
        'RegexParser\\Cache\\ArrayCache' => 'PHPRegex\\Parser\\Cache\\ArrayCache',
        'RegexParser\\Cache\\CacheInterface' => 'PHPRegex\\Parser\\Cache\\CacheInterface',
        'RegexParser\\Cache\\FilesystemCache' => 'PHPRegex\\Parser\\Cache\\FilesystemCache',
        'RegexParser\\Cache\\NullCache' => 'PHPRegex\\Parser\\Cache\\NullCache',
        'RegexParser\\Cache\\PsrCacheAdapter' => 'PHPRegex\\Parser\\Cache\\PsrCacheAdapter',
        'RegexParser\\Cache\\PsrSimpleCacheAdapter' => 'PHPRegex\\Parser\\Cache\\PsrSimpleCacheAdapter',
        'RegexParser\\Cache\\RemovableCacheInterface' => 'PHPRegex\\Parser\\Cache\\RemovableCacheInterface',
        'RegexParser\\Cli\\Application' => 'PHPRegex\\Cli\\Application',
        'RegexParser\\Cli\\Command\\AbstractCommand' => 'PHPRegex\\Cli\\Command\\AbstractCommand',
        'RegexParser\\Cli\\Command\\AnalyzeCommand' => 'PHPRegex\\Cli\\Command\\AnalyzeCommand',
        'RegexParser\\Cli\\Command\\ClearCacheCommand' => 'PHPRegex\\Cli\\Command\\ClearCacheCommand',
        'RegexParser\\Cli\\Command\\CommandInterface' => 'PHPRegex\\Cli\\Command\\CommandInterface',
        'RegexParser\\Cli\\Command\\CompareCommand' => 'PHPRegex\\Cli\\Command\\CompareCommand',
        'RegexParser\\Cli\\Command\\DebugCommand' => 'PHPRegex\\Cli\\Command\\DebugCommand',
        'RegexParser\\Cli\\Command\\DiagramCommand' => 'PHPRegex\\Cli\\Command\\DiagramCommand',
        'RegexParser\\Cli\\Command\\ExplainCommand' => 'PHPRegex\\Cli\\Command\\ExplainCommand',
        'RegexParser\\Cli\\Command\\GraphCommand' => 'PHPRegex\\Cli\\Command\\GraphCommand',
        'RegexParser\\Cli\\Command\\HelpCommand' => 'PHPRegex\\Cli\\Command\\HelpCommand',
        'RegexParser\\Cli\\Command\\HighlightCommand' => 'PHPRegex\\Cli\\Command\\HighlightCommand',
        'RegexParser\\Cli\\Command\\ParseCommand' => 'PHPRegex\\Cli\\Command\\ParseCommand',
        'RegexParser\\Cli\\Command\\RedosCommand' => 'PHPRegex\\Cli\\Command\\RedosCommand',
        'RegexParser\\Cli\\Command\\SelfUpdateCommand' => 'PHPRegex\\Cli\\Command\\SelfUpdateCommand',
        'RegexParser\\Cli\\Command\\TranspileCommand' => 'PHPRegex\\Cli\\Command\\TranspileCommand',
        'RegexParser\\Cli\\Command\\ValidateCommand' => 'PHPRegex\\Cli\\Command\\ValidateCommand',
        'RegexParser\\Cli\\Command\\VersionCommand' => 'PHPRegex\\Cli\\Command\\VersionCommand',
        'RegexParser\\Cli\\ConsoleStyle' => 'PHPRegex\\Cli\\ConsoleStyle',
        'RegexParser\\Cli\\GlobalOptions' => 'PHPRegex\\Cli\\GlobalOptions',
        'RegexParser\\Cli\\GlobalOptionsParser' => 'PHPRegex\\Cli\\GlobalOptionsParser',
        'RegexParser\\Cli\\Graph\\GraphGenerator' => 'PHPRegex\\Cli\\Graph\\GraphGenerator',
        'RegexParser\\Cli\\Graph\\GraphvizDumper' => 'PHPRegex\\Cli\\Graph\\GraphvizDumper',
        'RegexParser\\Cli\\Graph\\MermaidDumper' => 'PHPRegex\\Cli\\Graph\\MermaidDumper',
        'RegexParser\\Cli\\Input' => 'PHPRegex\\Cli\\Input',
        'RegexParser\\Cli\\Output' => 'PHPRegex\\Cli\\Output',
        'RegexParser\\Cli\\ParsedGlobalOptions' => 'PHPRegex\\Cli\\ParsedGlobalOptions',
        'RegexParser\\Cli\\SelfUpdate\\SelfUpdater' => 'PHPRegex\\Cli\\SelfUpdate\\SelfUpdater',
        'RegexParser\\Exception\\ComplexityException' => 'PHPRegex\\Automata\\Exception\\ComplexityException',
        'RegexParser\\Exception\\InvalidRegexOptionException' => 'PHPRegex\\Parser\\Exception\\InvalidRegexOptionException',
        'RegexParser\\Exception\\LexerException' => 'PHPRegex\\Parser\\Exception\\LexerException',
        'RegexParser\\Exception\\ParserException' => 'PHPRegex\\Parser\\Exception\\ParserException',
        'RegexParser\\Exception\\RecursionLimitException' => 'PHPRegex\\Parser\\Exception\\RecursionLimitException',
        'RegexParser\\Exception\\RegexException' => 'PHPRegex\\Parser\\Exception\\RegexException',
        'RegexParser\\Exception\\RegexParserExceptionInterface' => 'PHPRegex\\Parser\\Exception\\ExceptionInterface',
        'RegexParser\\Exception\\ResourceLimitException' => 'PHPRegex\\Parser\\Exception\\ResourceLimitException',
        'RegexParser\\Exception\\SemanticErrorException' => 'PHPRegex\\Parser\\Exception\\SemanticErrorException',
        'RegexParser\\Exception\\SyntaxErrorException' => 'PHPRegex\\Parser\\Exception\\SyntaxErrorException',
        'RegexParser\\Exception\\TranspileException' => 'PHPRegex\\Transpiler\\TranspileException',
        'RegexParser\\Exception\\VisualContextTrait' => 'PHPRegex\\Parser\\Exception\\VisualContextTrait',
        'RegexParser\\GroupNumbering' => 'PHPRegex\\Parser\\Analysis\\GroupNumbering',
        'RegexParser\\GroupNumberingCollector' => 'PHPRegex\\Parser\\Analysis\\GroupNumberingCollector',
        'RegexParser\\Internal\\PatternParser' => 'PHPRegex\\Parser\\Internal\\PatternParser',
        'RegexParser\\Lexer' => 'PHPRegex\\Parser\\Lexer',
        'RegexParser\\LintIssue' => 'PHPRegex\\Linter\\Rule\\RuleViolation',
        'RegexParser\\Lint\\Command\\LintArgumentParser' => 'PHPRegex\\Linter\\Config\\LintArgumentParser',
        'RegexParser\\Lint\\Command\\LintArguments' => 'PHPRegex\\Linter\\Config\\LintArguments',
        'RegexParser\\Lint\\Command\\LintCommand' => 'PHPRegex\\Cli\\Command\\LintCommand',
        'RegexParser\\Lint\\Command\\LintConfigLoader' => 'PHPRegex\\Linter\\Config\\LintConfigLoader',
        'RegexParser\\Lint\\Command\\LintConfigResult' => 'PHPRegex\\Linter\\Config\\LintConfigResult',
        'RegexParser\\Lint\\Command\\LintDefaultsBuilder' => 'PHPRegex\\Linter\\Config\\LintDefaultsBuilder',
        'RegexParser\\Lint\\Command\\LintExtractorFactory' => 'PHPRegex\\Linter\\Config\\LintExtractorFactory',
        'RegexParser\\Lint\\Command\\LintOutputRenderer' => 'PHPRegex\\Cli\\Command\\LintOutputRenderer',
        'RegexParser\\Lint\\Command\\LintParseResult' => 'PHPRegex\\Linter\\Config\\LintParseResult',
        'RegexParser\\Lint\\ExtractorInterface' => 'PHPRegex\\Linter\\Extraction\\ExtractorInterface',
        'RegexParser\\Lint\\Formatter\\AbstractOutputFormatter' => 'PHPRegex\\Linter\\Formatter\\AbstractOutputFormatter',
        'RegexParser\\Lint\\Formatter\\CheckstyleFormatter' => 'PHPRegex\\Linter\\Formatter\\CheckstyleFormatter',
        'RegexParser\\Lint\\Formatter\\ConsoleFormatter' => 'PHPRegex\\Linter\\Formatter\\ConsoleFormatter',
        'RegexParser\\Lint\\Formatter\\FormatterRegistry' => 'PHPRegex\\Linter\\Formatter\\FormatterRegistry',
        'RegexParser\\Lint\\Formatter\\GithubFormatter' => 'PHPRegex\\Linter\\Formatter\\GithubFormatter',
        'RegexParser\\Lint\\Formatter\\JsonFormatter' => 'PHPRegex\\Linter\\Formatter\\JsonFormatter',
        'RegexParser\\Lint\\Formatter\\JunitFormatter' => 'PHPRegex\\Linter\\Formatter\\JunitFormatter',
        'RegexParser\\Lint\\Formatter\\LinkFormatter' => 'PHPRegex\\Linter\\Formatter\\LinkFormatter',
        'RegexParser\\Lint\\Formatter\\OutputConfiguration' => 'PHPRegex\\Linter\\Formatter\\OutputConfiguration',
        'RegexParser\\Lint\\Formatter\\OutputFormatterInterface' => 'PHPRegex\\Linter\\Formatter\\OutputFormatterInterface',
        'RegexParser\\Lint\\Formatter\\RelativePathHelper' => 'PHPRegex\\Linter\\Formatter\\RelativePathHelper',
        'RegexParser\\Lint\\PhpRegexPatternSource' => 'PHPRegex\\Linter\\Source\\PhpFilePatternSource',
        'RegexParser\\Lint\\PhpStanExtractionStrategy' => 'PHPRegex\\Linter\\Extraction\\PhpParserExtractionStrategy',
        'RegexParser\\Lint\\RegexAnalysisService' => 'PHPRegex\\Linter\\AnalysisService',
        'RegexParser\\Lint\\RegexLintReport' => 'PHPRegex\\Linter\\LintReport',
        'RegexParser\\Lint\\RegexLintRequest' => 'PHPRegex\\Linter\\LintRequest',
        'RegexParser\\Lint\\RegexLintService' => 'PHPRegex\\Linter\\LintService',
        'RegexParser\\Lint\\RegexPatternExtractor' => 'PHPRegex\\Linter\\PatternExtractor',
        'RegexParser\\Lint\\RegexPatternOccurrence' => 'PHPRegex\\Linter\\PatternOccurrence',
        'RegexParser\\Lint\\RegexPatternSourceCollection' => 'PHPRegex\\Linter\\Source\\PatternSourceCollection',
        'RegexParser\\Lint\\RegexPatternSourceContext' => 'PHPRegex\\Linter\\Source\\PatternSourceContext',
        'RegexParser\\Lint\\RegexPatternSourceInterface' => 'PHPRegex\\Linter\\Source\\PatternSourceInterface',
        'RegexParser\\Lint\\TokenBasedExtractionStrategy' => 'PHPRegex\\Linter\\Extraction\\TokenBasedExtractionStrategy',
        'RegexParser\\LiteralExtractionResult' => 'PHPRegex\\Parser\\Analysis\\LiteralExtractionResult',
        'RegexParser\\LiteralSet' => 'PHPRegex\\Parser\\Analysis\\LiteralSet',
        'RegexParser\\NodeVisitor\\AbstractNodeVisitor' => 'PHPRegex\\Parser\\AbstractNodeVisitor',
        'RegexParser\\NodeVisitor\\AsciiTreeVisitor' => 'PHPRegex\\Explain\\AsciiTreeRenderer',
        'RegexParser\\NodeVisitor\\CompilerNodeVisitor' => 'PHPRegex\\Parser\\Printer\\PatternPrinter',
        'RegexParser\\NodeVisitor\\ComplexityScoreNodeVisitor' => 'PHPRegex\\Parser\\Analysis\\ComplexityScorer',
        'RegexParser\\NodeVisitor\\ConsoleHighlighterVisitor' => 'PHPRegex\\Explain\\Highlighter\\ConsoleHighlighter',
        'RegexParser\\NodeVisitor\\DumperNodeVisitor' => 'PHPRegex\\Parser\\Printer\\NodeDumper',
        'RegexParser\\NodeVisitor\\ExplainNodeVisitor' => 'PHPRegex\\Explain\\TextExplainer',
        'RegexParser\\NodeVisitor\\HighlighterVisitor' => 'PHPRegex\\Explain\\Highlighter\\AbstractHighlighter',
        'RegexParser\\NodeVisitor\\HtmlExplainNodeVisitor' => 'PHPRegex\\Explain\\HtmlExplainer',
        'RegexParser\\NodeVisitor\\HtmlHighlighterVisitor' => 'PHPRegex\\Explain\\Highlighter\\HtmlHighlighter',
        'RegexParser\\NodeVisitor\\LengthRangeNodeVisitor' => 'PHPRegex\\Parser\\Analysis\\LengthRangeCalculator',
        'RegexParser\\NodeVisitor\\LinterNodeVisitor' => 'PHPRegex\\Linter\\PatternLinter',
        'RegexParser\\NodeVisitor\\LiteralExtractorNodeVisitor' => 'PHPRegex\\Parser\\Analysis\\LiteralExtractor',
        'RegexParser\\NodeVisitor\\MermaidNodeVisitor' => 'PHPRegex\\Explain\\MermaidRenderer',
        'RegexParser\\NodeVisitor\\MetricsNodeVisitor' => 'PHPRegex\\Parser\\Analysis\\MetricsCollector',
        'RegexParser\\NodeVisitor\\ModernizerNodeVisitor' => 'PHPRegex\\Optimizer\\Modernizer',
        'RegexParser\\NodeVisitor\\NodeVisitorInterface' => 'PHPRegex\\Parser\\NodeVisitorInterface',
        'RegexParser\\NodeVisitor\\OptimizerNodeVisitor' => 'PHPRegex\\Optimizer\\Rewriter',
        'RegexParser\\NodeVisitor\\RailroadSvgVisitor' => 'PHPRegex\\Explain\\RailroadSvgRenderer',
        'RegexParser\\NodeVisitor\\ReDoSProfileNodeVisitor' => 'PHPRegex\\Redos\\RedosProfiler',
        'RegexParser\\NodeVisitor\\SampleGeneratorNodeVisitor' => 'PHPRegex\\Generator\\SampleGenerator',
        'RegexParser\\NodeVisitor\\TestCaseGeneratorNodeVisitor' => 'PHPRegex\\Generator\\TestCaseGenerator',
        'RegexParser\\NodeVisitor\\ValidatorNodeVisitor' => 'PHPRegex\\Parser\\Validation\\Validator',
        'RegexParser\\Node\\AbstractNode' => 'PHPRegex\\Parser\\Node\\AbstractNode',
        'RegexParser\\Node\\AlternationNode' => 'PHPRegex\\Parser\\Node\\AlternationNode',
        'RegexParser\\Node\\AnchorNode' => 'PHPRegex\\Parser\\Node\\AnchorNode',
        'RegexParser\\Node\\AssertionNode' => 'PHPRegex\\Parser\\Node\\AssertionNode',
        'RegexParser\\Node\\BackrefNode' => 'PHPRegex\\Parser\\Node\\BackrefNode',
        'RegexParser\\Node\\CalloutNode' => 'PHPRegex\\Parser\\Node\\CalloutNode',
        'RegexParser\\Node\\CharClassNode' => 'PHPRegex\\Parser\\Node\\CharClassNode',
        'RegexParser\\Node\\CharLiteralNode' => 'PHPRegex\\Parser\\Node\\CharLiteralNode',
        'RegexParser\\Node\\CharLiteralType' => 'PHPRegex\\Parser\\Node\\CharLiteralType',
        'RegexParser\\Node\\CharTypeNode' => 'PHPRegex\\Parser\\Node\\CharTypeNode',
        'RegexParser\\Node\\CommentNode' => 'PHPRegex\\Parser\\Node\\CommentNode',
        'RegexParser\\Node\\ConditionalNode' => 'PHPRegex\\Parser\\Node\\ConditionalNode',
        'RegexParser\\Node\\ControlCharNode' => 'PHPRegex\\Parser\\Node\\ControlCharNode',
        'RegexParser\\Node\\DefineNode' => 'PHPRegex\\Parser\\Node\\DefineNode',
        'RegexParser\\Node\\DotNode' => 'PHPRegex\\Parser\\Node\\DotNode',
        'RegexParser\\Node\\GroupNode' => 'PHPRegex\\Parser\\Node\\GroupNode',
        'RegexParser\\Node\\GroupType' => 'PHPRegex\\Parser\\Node\\GroupType',
        'RegexParser\\Node\\KeepNode' => 'PHPRegex\\Parser\\Node\\KeepNode',
        'RegexParser\\Node\\LimitMatchNode' => 'PHPRegex\\Parser\\Node\\LimitMatchNode',
        'RegexParser\\Node\\LiteralNode' => 'PHPRegex\\Parser\\Node\\LiteralNode',
        'RegexParser\\Node\\NodeInterface' => 'PHPRegex\\Parser\\Node\\NodeInterface',
        'RegexParser\\Node\\PcreVerbNode' => 'PHPRegex\\Parser\\Node\\PcreVerbNode',
        'RegexParser\\Node\\PosixClassNode' => 'PHPRegex\\Parser\\Node\\PosixClassNode',
        'RegexParser\\Node\\QuantifierNode' => 'PHPRegex\\Parser\\Node\\QuantifierNode',
        'RegexParser\\Node\\QuantifierType' => 'PHPRegex\\Parser\\Node\\QuantifierType',
        'RegexParser\\Node\\RangeNode' => 'PHPRegex\\Parser\\Node\\RangeNode',
        'RegexParser\\Node\\RegexNode' => 'PHPRegex\\Parser\\Node\\RegexNode',
        'RegexParser\\Node\\ScriptRunNode' => 'PHPRegex\\Parser\\Node\\ScriptRunNode',
        'RegexParser\\Node\\SequenceNode' => 'PHPRegex\\Parser\\Node\\SequenceNode',
        'RegexParser\\Node\\SubroutineNode' => 'PHPRegex\\Parser\\Node\\SubroutineNode',
        'RegexParser\\Node\\UnicodePropNode' => 'PHPRegex\\Parser\\Node\\UnicodePropNode',
        'RegexParser\\Node\\VersionConditionNode' => 'PHPRegex\\Parser\\Node\\VersionConditionNode',
        'RegexParser\\OptimizationResult' => 'PHPRegex\\Optimizer\\OptimizationResult',
        'RegexParser\\Parser' => 'PHPRegex\\Parser\\Syntax\\TokenParser',
        'RegexParser\\ProblemType' => 'PHPRegex\\Linter\\DiagnosticType',
        'RegexParser\\ReDoS\\CharSet' => 'PHPRegex\\Parser\\Analysis\\ByteCharSet',
        'RegexParser\\ReDoS\\CharSetAnalyzer' => 'PHPRegex\\Parser\\Analysis\\CharSetAnalyzer',
        'RegexParser\\ReDoS\\ReDoSAnalysis' => 'PHPRegex\\Redos\\RedosAnalysis',
        'RegexParser\\ReDoS\\ReDoSAnalyzer' => 'PHPRegex\\Redos\\RedosAnalyzer',
        'RegexParser\\ReDoS\\ReDoSConfidence' => 'PHPRegex\\Redos\\RedosConfidence',
        'RegexParser\\ReDoS\\ReDoSConfirmOptions' => 'PHPRegex\\Redos\\ConfirmationOptions',
        'RegexParser\\ReDoS\\ReDoSConfirmation' => 'PHPRegex\\Redos\\Confirmation',
        'RegexParser\\ReDoS\\ReDoSConfirmationRunner' => 'PHPRegex\\Redos\\ConfirmationRunner',
        'RegexParser\\ReDoS\\ReDoSConfirmationRunnerInterface' => 'PHPRegex\\Redos\\ConfirmationRunnerInterface',
        'RegexParser\\ReDoS\\ReDoSConfirmationSample' => 'PHPRegex\\Redos\\ConfirmationSample',
        'RegexParser\\ReDoS\\ReDoSFinding' => 'PHPRegex\\Redos\\Finding',
        'RegexParser\\ReDoS\\ReDoSHeatmap' => 'PHPRegex\\Redos\\Heatmap',
        'RegexParser\\ReDoS\\ReDoSHotspot' => 'PHPRegex\\Redos\\Hotspot',
        'RegexParser\\ReDoS\\ReDoSInputGenerator' => 'PHPRegex\\Redos\\Internal\\InputGenerator',
        'RegexParser\\ReDoS\\ReDoSMode' => 'PHPRegex\\Redos\\RedosMode',
        'RegexParser\\ReDoS\\ReDoSSeverity' => 'PHPRegex\\Redos\\RedosSeverity',
        'RegexParser\\Regex' => 'PHPRegex\\Toolkit\\Regex',
        'RegexParser\\RegexOptions' => 'PHPRegex\\Parser\\ParserOptions',
        'RegexParser\\RegexPattern' => 'PHPRegex\\Parser\\DelimitedPattern',
        'RegexParser\\RegexProblem' => 'PHPRegex\\Linter\\Diagnostic',
        'RegexParser\\Runtime\\PcreRuntimeInfo' => 'PHPRegex\\Cli\\PcreRuntimeInfo',
        'RegexParser\\Severity' => 'PHPRegex\\Linter\\LintSeverity',
        'RegexParser\\Token' => 'PHPRegex\\Parser\\Token\\Token',
        'RegexParser\\TokenStream' => 'PHPRegex\\Parser\\Token\\TokenStream',
        'RegexParser\\TokenType' => 'PHPRegex\\Parser\\Token\\TokenType',
        'RegexParser\\TolerantParseResult' => 'PHPRegex\\Parser\\TolerantParseResult',
        'RegexParser\\Transpiler\\RegexTranspiler' => 'PHPRegex\\Transpiler\\Transpiler',
        'RegexParser\\Transpiler\\Target\\JavaScript\\JavaScriptCompilerVisitor' => 'PHPRegex\\Transpiler\\Target\\JavaScript\\JavaScriptPrinter',
        'RegexParser\\Transpiler\\Target\\JavaScript\\JavaScriptTarget' => 'PHPRegex\\Transpiler\\Target\\JavaScript\\JavaScriptTarget',
        'RegexParser\\Transpiler\\Target\\Python\\PythonCompilerVisitor' => 'PHPRegex\\Transpiler\\Target\\Python\\PythonPrinter',
        'RegexParser\\Transpiler\\Target\\Python\\PythonTarget' => 'PHPRegex\\Transpiler\\Target\\Python\\PythonTarget',
        'RegexParser\\Transpiler\\Target\\TargetRegistry' => 'PHPRegex\\Transpiler\\Target\\TargetRegistry',
        'RegexParser\\Transpiler\\Target\\TranspileTargetInterface' => 'PHPRegex\\Transpiler\\Target\\TargetInterface',
        'RegexParser\\Transpiler\\TranspileContext' => 'PHPRegex\\Transpiler\\TranspileContext',
        'RegexParser\\Transpiler\\TranspileOptions' => 'PHPRegex\\Transpiler\\TranspileOptions',
        'RegexParser\\Transpiler\\TranspileResult' => 'PHPRegex\\Transpiler\\TranspileResult',
        'RegexParser\\ValidationErrorCategory' => 'PHPRegex\\Parser\\Validation\\ValidationErrorCategory',
        'RegexParser\\ValidationResult' => 'PHPRegex\\Parser\\Validation\\ValidationResult',
    ];

    /**
     * A 1.3 class gone in 2.0 => what to use instead.
     */
    public const REMOVED = [
        'RegexParser\\Automata\\RegexSolverInterface' => 'type against PHPRegex\\Automata\\LanguageSolver',
        'RegexParser\\Automata\\Solver\\RegexSolverCompilerInterface' => 'type against PHPRegex\\Automata\\LanguageSolver',
        'RegexParser\\Automata\\Solver\\RegexSolverInterface' => 'type against PHPRegex\\Automata\\LanguageSolver',
        'RegexParser\\Node\\ClassOperationNode' => 'no replacement: PHP reads "&&" and "--" in a class as members and ranges, so no pattern ever produced it',
        'RegexParser\\Node\\ClassOperationType' => 'no replacement: it only typed ClassOperationNode',
        'RegexParser\\Node\\UnicodeNode' => 'use PHPRegex\\Parser\\Node\\CharLiteralNode, which every \\x{...} and \\u{...} escape already became',
        'RegexParser\\ReDoS\\ReDoSAnalyzerInterface' => 'type against PHPRegex\\Redos\\RedosAnalyzer',
    ];

    /**
     * A 1.3 enum => [1.3 case => 2.0 case].
     */
    public const ENUM_CASES = [
        'RegexParser\\TokenType' => [
            'T_LITERAL' => 'Literal',
            'T_CHAR_TYPE' => 'CharType',
            'T_GROUP_OPEN' => 'GroupOpen',
            'T_GROUP_CLOSE' => 'GroupClose',
            'T_GROUP_MODIFIER_OPEN' => 'GroupModifierOpen',
            'T_CHAR_CLASS_OPEN' => 'CharClassOpen',
            'T_CHAR_CLASS_CLOSE' => 'CharClassClose',
            'T_QUANTIFIER' => 'Quantifier',
            'T_ALTERNATION' => 'Alternation',
            'T_DOT' => 'Dot',
            'T_ANCHOR' => 'Anchor',
            'T_EOF' => 'Eof',
            'T_RANGE' => 'Range',
            'T_NEGATION' => 'Negation',
            'T_BACKREF' => 'Backref',
            'T_UNICODE' => 'Unicode',
            'T_POSIX_CLASS' => 'PosixClass',
            'T_ASSERTION' => 'Assertion',
            'T_UNICODE_PROP' => 'UnicodeProp',
            'T_OCTAL' => 'Octal',
            'T_OCTAL_LEGACY' => 'OctalLegacy',
            'T_COMMENT_OPEN' => 'CommentOpen',
            'T_PCRE_VERB' => 'PcreVerb',
            'T_G_REFERENCE' => 'GReference',
            'T_KEEP' => 'Keep',
            'T_LITERAL_ESCAPED' => 'LiteralEscaped',
            'T_QUOTE_MODE_START' => 'QuoteModeStart',
            'T_QUOTE_MODE_END' => 'QuoteModeEnd',
            'T_CALLOUT' => 'Callout',
            'T_UNICODE_NAMED' => 'UnicodeNamed',
            'T_CONTROL_CHAR' => 'ControlChar',
        ],
        'RegexParser\\Node\\GroupType' => [
            'T_GROUP_CAPTURING' => 'Capturing',
            'T_GROUP_NON_CAPTURING' => 'NonCapturing',
            'T_GROUP_NAMED' => 'Named',
            'T_GROUP_LOOKAHEAD_POSITIVE' => 'LookaheadPositive',
            'T_GROUP_LOOKAHEAD_NEGATIVE' => 'LookaheadNegative',
            'T_GROUP_LOOKBEHIND_POSITIVE' => 'LookbehindPositive',
            'T_GROUP_LOOKBEHIND_NEGATIVE' => 'LookbehindNegative',
            'T_GROUP_INLINE_FLAGS' => 'InlineFlags',
            'T_GROUP_ATOMIC' => 'Atomic',
            'T_GROUP_BRANCH_RESET' => 'BranchReset',
        ],
        'RegexParser\\Node\\QuantifierType' => [
            'T_GREEDY' => 'Greedy',
            'T_LAZY' => 'Lazy',
            'T_POSSESSIVE' => 'Possessive',
        ],
        'RegexParser\\Node\\CharLiteralType' => [
            'UNICODE' => 'Unicode',
            'UNICODE_NAMED' => 'UnicodeNamed',
            'OCTAL' => 'Octal',
            'OCTAL_LEGACY' => 'OctalLegacy',
        ],
        'RegexParser\\ValidationErrorCategory' => [
            'SYNTAX' => 'Syntax',
            'SEMANTIC' => 'Semantic',
            'PCRE_RUNTIME' => 'PcreRuntime',
        ],
        'RegexParser\\ReDoS\\ReDoSSeverity' => [
            'SAFE' => 'Safe',
            'LOW' => 'Low',
            'MEDIUM' => 'Medium',
            'UNKNOWN' => 'Unknown',
            'HIGH' => 'High',
            'CRITICAL' => 'Critical',
        ],
        'RegexParser\\ReDoS\\ReDoSMode' => [
            'OFF' => 'Off',
            'THEORETICAL' => 'Theoretical',
            'CONFIRMED' => 'Confirmed',
        ],
        'RegexParser\\ReDoS\\ReDoSConfidence' => [
            'LOW' => 'Low',
            'MEDIUM' => 'Medium',
            'HIGH' => 'High',
        ],
        'RegexParser\\Automata\\Options\\MatchMode' => [
            'FULL' => 'Full',
            'PARTIAL' => 'Partial',
        ],
        'RegexParser\\Automata\\Minimization\\MinimizationAlgorithm' => [
            'HOPCROFT' => 'Hopcroft',
            'MOORE' => 'Moore',
        ],
        'RegexParser\\Automata\\Determinization\\DeterminizationAlgorithm' => [
            'SUBSET' => 'Subset',
            'SUBSET_INDEXED' => 'SubsetIndexed',
        ],
        'RegexParser\\Bridge\\Symfony\\Analyzer\\Severity' => [
            'PASS' => 'Pass',
            'WARN' => 'Warn',
            'FAIL' => 'Fail',
            'CRITICAL' => 'Critical',
        ],
    ];

    /**
     * [1.3 class, 1.3 method, 2.0 method].
     */
    public const METHODS = [
        ['RegexParser\\Lint\\RegexAnalysisService', 'getRegex', 'getParser'],
        ['RegexParser\\Automata\\Api\\RegexLanguageSolver', 'intersectionEmpty', 'intersection'],
        ['RegexParser\\Automata\\Api\\RegexLanguageSolver', 'prepare', 'compile'],
        ['RegexParser\\Regex', 'clearValidatorCaches', 'clearCaches'],
    ];
}
